[package]
name = "detective"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "2.0.0"
rocket = "0.5.0-rc.1"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
